development:
  adapter: postgresql
  encoding: unicode
  database: checkers_development

test:
  adapter: postgresql
  encoding: unicode
  database: checkers_test

production:
  adapter: postgresql
  encoding: unicode
  database: checkers_production
